language: java
script:
  - jdk_switcher use oraclejdk8
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
stage: GitHub Release
  script: echo "Deploying to GitHub releases ..."
  deploy:
     provider: releases
     api_key:
         secure: [redacted]
     file:
         - server/target/*.jar
         - README.md
     skip_cleanup: true
     on:
         repo: patrickeklund/automaticBuild
         tags: true
#  deploy:
#    provider: releases
#    api_key: $GITHUB_OAUTH_TOKEN
#    skip_cleanup: true
#    on:
#       tags: true


#before_deploy:
#  # Set up git user name and tag this commit
#  - git config --local user.name "YOUR GIT USER NAME"
#  - git config --local user.email "YOUR GIT USER EMAIL"
#  - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
#deploy:
#  provider: releases
#  api_key: "GITHUB OAUTH TOKEN"
#  file: "FILE TO UPLOAD"
#  skip_cleanup: true
