language: java
stages:
  - buildCode
  - createTag
  - deployToGitHub
jobs:
  include:
    - stage: buildCode
      script:
        - echo "Building Code..."
        - jdk_switcher use oraclejdk8
        - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
    - stage: createTag
      # require the branch name to be master
      if: branch = master
      script:
## CREATE GIT TAG
#- git config --global user.email "builds@travis-ci.com"
#- git config --global user.name "Travis CI"
#- export GIT_TAG=build-$TRAVIS_BRANCH-$(date -u "+%Y-%m-%d")-$TRAVIS_BUILD_NUMBER
#- echo -n $GIT_TAG > public/version
#- git commit -m "Set build VERSION number" public/version
#- git tag $GIT_TAG -a -m "Generated tag from TravisCI build $TRAVIS_BUILD_NUMBER"
#- git push --quiet https://$GITHUBKEY@github.com/dev-confidence/example-backend-api $GIT_TAG > /dev/null 2>&1
        - echo "Creating Tag..."
        - git config --local travis.slug
#        - git config --local user.name "patrickeklund"
#        - git config --local user.email "patrickeklund@hotmail.com"
#        - git tag "$(date +'%Y%m%d')-$(git log --format=%h -1)"
#        - git push --tags
    - stage: deployToGitHub
      deploy:
        provider: releases
        api_key:
          secure: [redacted]
        script:
          - echo "Deploy To Github..."
        file:
          - server/target/*.jar
          - README.md
        skip_cleanup: true
        on:
          repo: patrickeklund/automaticBuild
          tags: true
#  deploy:
#    provider: releases
#    api_key: $GITHUB_OAUTH_TOKEN
#    skip_cleanup: true
#    on:
#       tags: true


#before_deploy:
#  # Set up git user name and tag this commit
#  - git config --local user.name "YOUR GIT USER NAME"
#  - git config --local user.email "YOUR GIT USER EMAIL"
#  - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
#deploy:
#  provider: releases
#  api_key: "GITHUB OAUTH TOKEN"
#  file: "FILE TO UPLOAD"
#  skip_cleanup: true
