language: java
dist: trusty
sudo: required
services:
- docker
stages:
- buildCode
- createTag
- deployToGitHub
jobs:
  include:
  - stage: buildCode
    script:
    - echo
    - echo "Building Code..."
    - jdk_switcher use oraclejdk8
    - mvn clean install -T4C
    - echo
    - echo "Building Docker image"
    - docker build --pull --tag patrickeklund/automaticbuild:build-$TRAVIS_BRANCH-$(date
      +'%Y-%m-%d')-$TRAVIS_BUILD_NUMBER --file server/src/resources/docker/Dockerfile
      server
    - echo
    - echo "Creating Docker tag latest"
    - docker tag patrickeklund/automaticbuild:build-$TRAVIS_BRANCH-$(date +'%Y-%m-%d')-$TRAVIS_BUILD_NUMBER
      latest
    - echo
    - echo "login to DockerHub..."
    - docker login -u $DOCKERHUB_USER -p $DOCKERHUB_USER_PASSWORD -e $DOCKER_HUB_USER_EMAIL  
    - echo
    - echo "Deploy docker image to DockerHub..."
    - docker push patrickeklund/automaticbuild:build-$TRAVIS_BRANCH-$(date +'%Y-%m-%d')-$TRAVIS_BUILD_NUMBER
    - docker push latest
  - stage: createTag
    if: branch = master
    script:
    - echo
    - echo "Creating Tag..."
    - git config --local user.name ${BUILD_USER}
    - git config --local user.email ${BUILD_USER_EMAIL}
    - git tag "build-$TRAVIS_BRANCH-$(date +'%Y-%m-%d')-$TRAVIS_BUILD_NUMBER"
    - echo
    - echo "Pushing Tag to GithHub..."
    - git push --tags --quiet https://${GITHUB_PERSONAL_ACCESS_TOKEN}@github.com/patrickeklund/automaticBuild.git
      > /dev/null 2>&1
    - echo
    - echo "Deploy docker image to DockerHub..."
    - docker push patrickeklund/automaticbuild:"build-$TRAVIS_BRANCH-$(date +'%Y-%m-%d')-$TRAVIS_BUILD_NUMBER"
    - docker push latest
  - stage: deployToGitHub
    deploy:
      provider: releases
      api_key:
        secure: "${GITHUB_PERSONAL_ACCESS_TOKEN}"
      script:
      - echo "Building Code..."
      - jdk_switcher use oraclejdk8
      - mvn clean install -T4C
      - echo
      - echo "Building Docker image"
      - docker build --pull --tag patrickeklund/automaticbuild:"build-$TRAVIS_BRANCH-$(date
        +'%Y-%m-%d')-$TRAVIS_BUILD_NUMBER" --file server/src/resources/docker/Dockerfile
        server
      - echo
      - echo "Creating Docker tag latest"
      - docker tag patrickeklund/automaticbuild:build-$TRAVIS_BRANCH-$(date +'%Y-%m-%d')-$TRAVIS_BUILD_NUMBER
        latest
      - echo "Deploy docker image to DockerHub..."
      - echo
      - docker push patrickeklund/automaticbuild:build-$TRAVIS_BRANCH-$(date +'%Y-%m-%d')-$TRAVIS_BUILD_NUMBER
      - docker push latest
      - echo
      - echo "Deploy build artifacts To Github..."
      file_glob: true
      file:
      - server/target/server-*.jar
      - README.md
      skip_cleanup: true
      on:
        repo: patrickeklund/automaticBuild
        tags: true
env:
  global:
  - BUILD_USER="Travis CI"
  - BUILD_USER_EMAIL="builds@travis-ci.com"
  - secure: BlB88SGMw2SyXJG0RqQExnAeVbMt9RPpMD8Tw+AmvPQVylqUTIzkzYzSiEXiOCts6L2l/a2IGJxh9qtDZGZi1nJAOYGoZQRITHBVfDWqAPVL6z+gSiQfWDUBJKZ1pMWnKN2a+8Zm/v2Owc0EmQUE1CXg12YcC34/LbECZNP9sLZOkFAy5tD9XsXno4F1E2x3kySyseKzjvY+t6cCIYIOLVvRZt3tMUI9F6Lb0azb3cxg+4hlTEQB/X47F80XLSk6R2QKK5uGLKwwJmFuvooRGvj8XI0/na5UyrPkwEr/RrYzAF8foDuudc/utEA8ffzJFP1JgGhwdBu7CDV8o+vaJWU7B5Kcnz2+e6mHQOJJv1OUeTtToAL3O0hooOjNtw3pigdXTGNlAhOrSRfBKZnUobSohppOI/WtiCEugQiAKoaWZ7JC1aCHtDPrXIT+ubbPBI7/pN0K8IsTWJ508W2ukdIzhDQ5kJ0uGJCEPuFJso/DlVwmDPjzMf7BOM6iT01oksBk4dJMCahIKEnktle/1Gv0PGK4wLbFkOCREb1HZXvw+LUdEDUSv3P46pCfELdhTELfhaV7FegOE17KXQ35jygzZ8ZbR7omR244umyZn0tUqd5tAquO6Zma0K2VVLyCakYbkjuglJoXdXaf2babWfKMfx2zBPZQDXirnHyBO8E=
  - secure: iDaRMi3PX+AAe/xjEspZ92nMpK+3CczNct9dQbv/Wee3oK4aAKQcKHV3pxUa88qWReKD8NvJx/LKYzu1/89bwKKPcaBqiLBFj/tdZjcKbfd/9lSWZ4uy/W7tkOCz+22Btp/7jv4Cp4+9XE69tESs4pUGetKkJQ3WIb7X0J/7jT7yme3wb/meeLON8dYr8KcFGcFlOLdYh5vQf3QGgv8bPIAdFxU1LHUz52ol6Rr2ZVm5OZPNZKBcDk9AzbG/o0/Ufg5qxzktlEG9lDDkKValepKYeL9GArL7ZQWkFu0fkxqlD7QInAo3dQ9izTCEYevfyOF6y6zvkHcQBk+o5yf7UveQOLj4lDxNoXBWuq/E7rkZH7AOcLKzlTjDZnNyeTc4HmAvGd0vy9AfvBYw8Co8ZyvGwpUUn8/qaXiobCQGS0DmjRdUukXwm+A3fy9dGCwte/iZYblFZzv5Sn3682OzEUqQEh6P4K+siPp4w8X/8wMLs8kOG3bVFoljYlgBwBv8K6fIo/8L6h9pOL148q1CcfPxNniHDY/ewjsFdLcPV5soLvec/LPnmJaO+7vIMjx5PZsXSmn4S1jQ7oQZunM593I8dt0aqWM5YJIuz0yCNsHc/e+ruOoeerMSrheHmSMvup0dVonVIGAb4+dasSMjFVbB8wcKkGR3jpajJKBlvX0=
  - secure: yDnuzWwN6xpWoePefbBICdEri2qttwOHwmPY6/AimAQl0EJWoaWu3FbwKlw+MSbMbfNLksf4+3QNZ9HAIHi90h74Yo3/9F6ZTNHJ1oP2uFVz35GfxDcYSV55T7BE37da8VblgZlUPoMmbVfBJxoxtgVZoM8uqrnCj6pX3D6BUpgVDsWV7hCCd49Hx0eSWBOiBhnMw+Z36zDf2KPCdfF0nImPvJCojC/psqiigYlBGHOhsYS058KT5zAESaY6H9qq0u1OYEkEFud2ZYWzRMHTMda1InN8HmEvr6cGgHUQ5xhdTPFIMgPsHWDuO12baAXgRJDzc0TSM+50Dt2SBfdjVIvXK10fwX0JWsyeyoO7V97qWODXbaHccChTpZhel9Hi6K8Jy+Phv4EUHrC0E0dWGsGdai+bILo3juOof9Q0X9C2lIXxFIP2IeF7b73dJr8BA6MV3Fn9s+zeUAhogkuAjxsxgmXXcCgvFinTUYjRkRhjXOp2vXKQ/ENOrIOq/MtONW7cA7s0HEwG9oW/U5x0Zzb1Cq4ovOHmP9tXsK/fhLAZzMKLtNUwyuFiYE4IgcBppRFDm+N68RLN5rdbIz26fPd2FnOdwQWF/wt3NXhUYUYL5qMocH5mVFpXya/VgQ2T5WtFAjh1uUNN4UdqXwhjfwkcDF6cWouKvSxefIOj5SI=
  - secure: uA4gRWDIDtezKq7JuXESfhdA/feNeU9439wwvDAZd6hUVbDHK3mPJLV3d5IRLy8PqyiWBeeYFAfGmVORDB9L88A8eKjF1yygordwaGH+ZRc2HQ8UGe4lIKt1d7OObj6P6Jk8EZckFZxNUhGMdtIsikTgvRRAdqeci+KMdo1Ec/mxllPwpj8gsfjXLfPBS+h0jbSVkI/4mY8ATomwrZZRFu6BjfjZs615UHb3YFExHD88m386ZA1hNcBAR+VMbc5lyTHIGr2H2ep7i50x1gwrV16WOYBcZmj28dog2pQhUF15ba/8FvVTHT4SZsvXFsrOnbx8rHJtSKM4pAcawnvyqPCFvqpWCFPgL+k36yMTMi3F2YQyv+yCUlgQWTCpmrPqWp0Vwen+AJnAzw7zM2GoLgCBKlOgJTIgR065IG/y7VY/sxDSp90vDnIswBxlOiQGkQVjvO7jfxrJU5ITnysNVjA7zOAl2gbBMoW55uh56O04OLgu6gcJmyZzDS2flioTIojim+wpOeJchSVOCpggkXeMVhoPdM503N3JFXAEaZ9kO2ikFFl+DWAmweanR21V9VaNAhiWe1hRv7MNe4+agyfOBcFfMR/ahsbM5DnQLU+1Ilaexg34m2izC+F1MDslLKhhlhspOHkFyVXIFj1QOqutHb4nQhQY+XabtW7anx4=
