language: java
dist: trusty
sudo: required
services:
- docker
stages:
- buildCode
- createTag
- deployToGitHub
jobs:
  include:
  - stage: buildCode
    script:
    - echo
    - echo "Building Code..."
    - jdk_switcher use oraclejdk8
    - mvn clean install -T4C
    - echo
    - echo "Building Docker image"
    - docker build --pull --tag patrickeklund/automaticbuild:build-$TRAVIS_BRANCH-$(date
      +'%Y-%m-%d')-$TRAVIS_BUILD_NUMBER --file server/src/resources/docker/Dockerfile
      server
    - echo
    - echo "Creating Docker tag latest"
    - docker tag patrickeklund/automaticbuild:build-$TRAVIS_BRANCH-$(date +'%Y-%m-%d')-$TRAVIS_BUILD_NUMBER
      latest
    - echo
    - echo "login to DockerHub..."
    - docker login --username $DOCKERHUB_USER --password $DOCKERHUB_USER_PASSWORD
    - echo
    - echo "Deploy docker image to DockerHub..."
    - docker push patrickeklund/automaticbuild:build-$TRAVIS_BRANCH-$(date +'%Y-%m-%d')-$TRAVIS_BUILD_NUMBER
    - docker push latest
  - stage: createTag
    if: branch = master
    script:
    - echo
    - echo "Creating Tag..."
    - git config --local user.name ${BUILD_USER}
    - git config --local user.email ${BUILD_USER_EMAIL}
    - git tag "build-$TRAVIS_BRANCH-$(date +'%Y-%m-%d')-$TRAVIS_BUILD_NUMBER"
    - echo
    - echo "Pushing Tag to GithHub..."
    - git push --tags --quiet https://${GITHUB_PERSONAL_ACCESS_TOKEN}@github.com/patrickeklund/automaticBuild.git
      > /dev/null 2>&1
  - stage: deployToGitHub
    deploy:
      provider: releases
      api_key:
        secure: "${GITHUB_PERSONAL_ACCESS_TOKEN}"
      script:
      - echo "Building Code..."
      - jdk_switcher use oraclejdk8
      - mvn clean install -T4C
      - echo
      - echo "Building Docker image"
      - docker build --pull --tag patrickeklund/automaticbuild:"build-$TRAVIS_BRANCH-$(date
        +'%Y-%m-%d')-$TRAVIS_BUILD_NUMBER" --file server/src/resources/docker/Dockerfile
        server
      - echo
      - echo "Creating Docker tag latest"
      - docker tag patrickeklund/automaticbuild:build-$TRAVIS_BRANCH-$(date +'%Y-%m-%d')-$TRAVIS_BUILD_NUMBER
        latest
      - echo
      - echo "login to DockerHub..."
      - docker login --username $DOCKERHUB_USER --password $DOCKERHUB_USER_PASSWORD
      - echo
      - echo "Deploy docker image to DockerHub..."
      - docker push patrickeklund/automaticbuild:build-$TRAVIS_BRANCH-$(date +'%Y-%m-%d')-$TRAVIS_BUILD_NUMBER
      - docker push latest
      - echo
      - echo "Deploy build artifacts To Github..."
      file_glob: true
      file:
      - server/target/server-*.jar
      - README.md
      skip_cleanup: true
      on:
        repo: patrickeklund/automaticBuild
        tags: true
env:
  global:
  - BUILD_USER="Travis CI"
  - BUILD_USER_EMAIL="builds@travis-ci.com"
  - secure: BlB88SGMw2SyXJG0RqQExnAeVbMt9RPpMD8Tw+AmvPQVylqUTIzkzYzSiEXiOCts6L2l/a2IGJxh9qtDZGZi1nJAOYGoZQRITHBVfDWqAPVL6z+gSiQfWDUBJKZ1pMWnKN2a+8Zm/v2Owc0EmQUE1CXg12YcC34/LbECZNP9sLZOkFAy5tD9XsXno4F1E2x3kySyseKzjvY+t6cCIYIOLVvRZt3tMUI9F6Lb0azb3cxg+4hlTEQB/X47F80XLSk6R2QKK5uGLKwwJmFuvooRGvj8XI0/na5UyrPkwEr/RrYzAF8foDuudc/utEA8ffzJFP1JgGhwdBu7CDV8o+vaJWU7B5Kcnz2+e6mHQOJJv1OUeTtToAL3O0hooOjNtw3pigdXTGNlAhOrSRfBKZnUobSohppOI/WtiCEugQiAKoaWZ7JC1aCHtDPrXIT+ubbPBI7/pN0K8IsTWJ508W2ukdIzhDQ5kJ0uGJCEPuFJso/DlVwmDPjzMf7BOM6iT01oksBk4dJMCahIKEnktle/1Gv0PGK4wLbFkOCREb1HZXvw+LUdEDUSv3P46pCfELdhTELfhaV7FegOE17KXQ35jygzZ8ZbR7omR244umyZn0tUqd5tAquO6Zma0K2VVLyCakYbkjuglJoXdXaf2babWfKMfx2zBPZQDXirnHyBO8E=
  - secure: DDbmLpDGxqw4lXNDmU0tSs03b6ur/RVMUeQefI8a0a35Q9hI+3urAd7ulSmRbYCMRO7FYNU0Rjn4VevRmDzomqErfPgVvxPX/F6k1cgMr3Y+iTjlcseRL2LDuquWZo7FFMowbBXJE+HrrUXzt7d+d9RRhs2PYqP6IHbhqm2RbDEhNFK6eu9mVD86AoGyEQJkTWBdVuz8GpxNtz8RU9pf/vHoCl5AzO2GUgaWURBjPDh4BE2NGUl+8NL+MJMyKIzjlAx0haIF/jzvZ/cPL0YnC9CBZwVzfm9VppbM3PInH/VS/EtDPdkFZvSoJMqadzUP0IdhlS7Z+3Vz+12UxHaFsnPrZTG7vtimpfCn3z5kqoH/qQ0B6rrK/LnpdGCji67WU/XOtmJJftXEFZb1iqQPhUIagsRlcGYusynCs09t/XtOmHnETHGGcyf/H0VSpc/QO/VNJ8nIDuQqzv6mEroEkxmAIGl+9lI3IjG+FxqOYxB9k0qzDYYTO5uxQVZz/QYp6MQC4+fHvIBjXzllfjlqWD2UGWJD5+uPac/FPqZS7W2k1tXv3h5E6RMYyHIJqqPlPNeM5NhmMmmU/75XJ2QSI0h74BCqK1O1Yr76X4i8/v+aL3dg6mvSsUK2A8tbGWgCu2UkcFuAaHq8wHv5huPLmPrYN/g6lhF1LLQWLNeTIFE=
  - secure: WUUg+BbKOiOG4t5/2Hkngs03fOScYbA5J9hp82zLakCT7JQSqJbFldoBUKUvTmkahhv5fRYZ04eqDW58mDm/2kLcDzJzbR4qF9p1maEjWVBRUH/HXbC6jwRbdkH6xo9Cae4vIvm76AjPH6I4/Wmv1ZOMdsX/CxUhvM/SJ8SbWabIP/Juw9IijyQa7sI3SP7k2dEhbYiZ32vYXz9YGGI7ZgbsY8oGzhOQupY35AauJrbAaWjl389eyfTpCAQYxPRjyjX32DQMbWzem9swvhM3T8/16s84NzKZrFqaMLSylhEHnIVkxVg4mdlX98VOqPrzEn5ngZ7lCVyB+ApRkC8EnVDl9q4av1glJA6YZkd9JcKKy4TBwc6x+dayCkl4GDhR+zZ7lKT1nL8dUdw5aXi4QDYDiCD6i7S7e1ewFBnnR4ulW7qFF1zoSnbYMgnCutJ/9MdejTA3HkOazn9lkDfCaznO5teoPrsOjHgH5UFzGU9VLf6WeYIjBp860sPS13qsKC7kQQWIqWzzL2EZL9Owf8dKtf1S6zHzss8EMHa5/Ftl5h+UTdK00KvdrAjErxCMwcdGieEZNrgSDrrEEHDpfdABG9TAVoeDDQMo0MLrBR/+YdtL/3V9tMu4LuuwCUcKShYaT9bBJa7OfrKqolVcpcMh9jCHzMCkgM4aGsrsG/k=
