#
# This file contains configuration flags to customize your site
#

# Theme to use
theme: jekyll-theme-architect

# Name and Title of your site (displayed in the header)
title: Automatic Build
name: Patrick Eklund

# Short bio or description (displayed in the header)
description: Developed and Maintained by Patrick Eklund

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://github.com/patrickeklund.png

# Enable downloads
show_downloads: true

permalink:   /:categories/:posts/:title/
